<h1 style="color:#ff5733; text-align:center; font-size:45px;">🚀 Hello! I'm <b style="color:#33A1FF;">Yahya Ahmad</b> 👋</h1>

<p style="font-size:22px; text-align:center; color:#444;">
I'm a beginner passionate about <b style="color:#FF914D;">technology</b>, <b style="color:#FF914D;">machine learning</b>, and <b style="color:#FF914D;">Python programming</b>. 
I'm excited to learn and grow in the world of <b style="color:#33A1FF;">data science</b> and <b style="color:#33A1FF;">AI</b>. 🚀
</p>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#33A1FF; font-size:30px;">🎯 My Interests:</h2>

<ul style="font-size:22px; color:#444;">
    <li><b style="color:#FF914D;">Programming</b>: Python </li>
    <li><b style="color:#FF914D;">Machine Learning</b>: Exploring PyTorch and TensorFlow</li>
    <li><b style="color:#FF914D;">Deep Learning AI</b>: Neural Networks & Computer Vision</li>
</ul>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#33A1FF; font-size:30px;">📬 Let's Connect!</h2>

<ul style="font-size:22px; color:#444;">
    <li>📧 <b>Email</b>: <a href="mailto:Ya0280780@gmail.com" style="color:#FF914D;">Ya0280780@gmail.com</a></li>
    <li>🔗 <b>LinkedIn</b>: <a href="https://www.linkedin.com/in/yahya-ahmad-8538312b1/" style="color:#FF914D;">Yahya Ahmad on LinkedIn</a></li>
    <li>💻 <b>GitHub</b>: <a href="https://github.com/Yahyaahmad09/Courses" style="color:#FF914D;">My GitHub Repository</a></li>
</ul>

<hr style="border:2px solid #ff5733; width:80%;">


<h1 style="color:#ff6600;">📌 Dataset and DataLoader in PyTorch</h1>

<h2 style="color:#3366cc;">1️⃣ What is a Dataset class?</h2>
<p>
A <b>Dataset</b> in PyTorch is a class that helps load and preprocess data. It is usually created by subclassing <code>torch.utils.data.Dataset</code> and defining <code>__len__</code> and <code>__getitem__</code> methods.
</p>

<h2 style="color:#3366cc;">2️⃣ What is a DataLoader class?</h2>
<p>
The <b>DataLoader</b> in PyTorch helps in efficient data loading by handling <i>batching, shuffling, and multiprocessing</i>. It works with any dataset that follows the <code>Dataset</code> class structure.
</p>

<h2 style="color:#ff6600;">✅ Key Benefits</h2>
<ul>
    <li><b>Efficient Data Loading:</b> Handles large datasets by loading them in small batches.</li>
    <li><b>Shuffling:</b> Randomizes data order to improve training.</li>
    <li><b>Parallel Processing:</b> Uses multiple workers for faster data loading.</li>
</ul>

<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#3366cc;">📌 Import the Necessary Libraries</h2>
<p>Before we begin, let's import the required libraries for working with datasets and dataloaders in PyTorch.</p>

<h2 style="color:#ff6600;">🔹 Convert the Data into PyTorch Tensors</h2>
<p>We need to convert our data into PyTorch tensors for compatibility with PyTorch models.</p>

<h2 style="color:#3366cc;">🚀 Let's Start Our Workflow</h2>

<h3 style="color:#ff6600;">1️⃣ Create a Custom Dataset Class</h3>
<p>We define a custom dataset class by implementing three main functions: <code>__init__</code>, <code>__len__</code>, and <code>__getitem__</code>.</p>

<h3 style="color:#ff6600;">2️⃣ Create an Object of the Dataset Class</h3>
<p>We instantiate the dataset class to store and manage our data efficiently.</p>

<h3 style="color:#3366cc;">3️⃣ Create an Object of the DataLoader Class</h3>
<p>The DataLoader will help us load the dataset efficiently with batching and shuffling.</p>

<h3 style="color:#ff6600;">4️⃣ Use a Loop to Print or Show the Batches</h3>
<p>Finally, we use a loop to iterate through the DataLoader and display the data in batches.</p>

<hr style="border:2px solid #ff5733; width:80%;">


<h1 style="color:#ff6600;">Simple Code Example for Dataset and DataLoader classes</h1>

<h2 style="color:#3366cc;">Import the Necessary Labraries</h2>

In [12]:
from sklearn.datasets import make_classification
import torch
from torch.utils.data import Dataset, DataLoader

In [4]:
# step 01: create a synthetic classification dataset using sklearn 
X, y = make_classification(
    n_samples=10,          # Number of samples
    n_features=2,          # Number of features
    n_informative=2,       # Number of  inforative features
    n_redundant=0,         # Number of Redundant features (No dulicate )
    n_classes=2,           # Number of classes 
    random_state=42        # For reproductivity
)

In [5]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [6]:
X.shape

(10, 2)

In [7]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [8]:
y.shape

(10,)

In [9]:
# convert the data into pytorch Tensor 
X = torch.tensor(X, dtype = torch.float32)
y = torch.tensor(y, dtype = torch.long)

In [10]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

<h2 style="color:#3366cc;">Let's start our work flow</h2>

In [22]:
# create a custom class in whcih three man functions
class CustomDataSet(Dataset):
# 1:- __init__()
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
        
# 2:- __len__()
    def __len__(self):
        return self.features.shape[0]

# # 3:- __getitem__()
    def __getitem__(self, index):
        return self.features[index], self.labels[index]


In [23]:
# create an object of the class
dataset = CustomDataSet(X, y)

In [24]:
len(dataset)

10

In [26]:
dataset[4]

(tensor([-1.9629, -0.9923]), tensor(0))

In [29]:
# create the object of DataLoader class
dataloader = DataLoader(dataset,batch_size=2, shuffle=True)

In [34]:
# Use for loop to print or show the Batches
for batch_features, batch_labels in dataloader:
    print(batch_features),
    print(batch_labels),
    print('-'*50)

tensor([[-0.7206, -0.9606],
        [-2.8954,  1.9769]])
tensor([0, 0])
--------------------------------------------------
tensor([[1.7774, 1.5116],
        [1.8997, 0.8344]])
tensor([1, 1])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [ 1.7273, -1.1858]])
tensor([0, 1])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------


<h1 style="color:#ff6600; text-align:center;">📊 Breast Cancer Dataset Training Pipeline</h1>

<p style="font-size:22px; text-align:center; color:#444;">
The training pipeline consists of the following steps:
</p>
<h2 style="color:#33A1FF; font-size:30px;">📜 Code Flow</h2>


<p style="font-size:22px; text-align:center; color:#444;">
The training pipeline consists of the following steps:
</p>

<ol style="font-size:22px; color:#444;">
    <li>✅ Load the dataset</li>
    <li>✅ Basic preprocessing</li>
    <li>🚀 Training Process:
        <ul>
            <li>✅ Create the model</li>
            <li>🔹 Forward pass</li>
            <li>🔹 Loss calculation</li>
            <li>🔹 Backpropagation</li>
            <li>🔹 Parameter update</li>
        </ul>
    </li>
    <li>📊 Model evaluation</li>
</ol>


<hr style="border:2px solid #ff5733; width:80%;">

<h2 style="color:#ff6600;">📌 Import the Necessary Libraries</h2>
<p>Before we begin, let's import the required libraries for working with datasets and dataloaders in PyTorch.</p>

<h2 style="color:#3366cc;">🔹 Convert the Data into PyTorch Tensors</h2>
<p>We need to convert our data into PyTorch tensors for compatibility with PyTorch models.</p>

<h2 style="color:#ff6600;">🚀 Let's Start Our Workflow</h2>

<h3 style="color:#3366cc;">1️⃣ Create a Custom Dataset Class</h3>
<p>We define a custom dataset class by implementing three main functions: <code>__init__</code>, <code>__len__</code>, and <code>__getitem__</code>.</p>

<h3 style="color:#ff6600;">2️⃣ Create an Object of the Dataset Class</h3>
<p>We instantiate the dataset class to store and manage our data efficiently.</p>

<h3 style="color:#3366cc;">3️⃣ Create an Object of the DataLoader Class</h3>
<p>The DataLoader will help us load the dataset efficiently with batching and shuffling.</p>

<h3 style="color:#ff6600;">4️⃣ Use a Loop to Print or Show the Batches</h3>
<p>Finally, we use a loop to iterate through the DataLoader and display the data in batches.</p>

<hr style="border:2px solid #ff5733; width:80%;">


In [35]:
# import the necessary labraries
import torch
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [36]:
# Read CSV file
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/master/data.csv")

In [75]:
df.drop(columns=['id','Unnamed: 32'], inplace = True)

In [76]:
df.head()

diagnosis  radius_mean  texture_mean  ...  concave points_worst  symmetry_worst  fractal_dimension_worst
0        NaN        17.99         10.38  ...                0.2654          0.4601                  0.11890
1        NaN        20.57         17.77  ...                0.1860          0.2750                  0.08902
2        NaN        19.69         21.25  ...                0.2430          0.3613                  0.08758
3        NaN        11.42         20.38  ...                0.2575          0.6638                  0.17300
4        NaN        20.29         14.34  ...                0.1625          0.2364                  0.07678

[5 rows x 31 columns]

In [100]:
# See the shape of the data 
df.shape

(569, 31)

In [78]:
df = df.apply(pd.to_numeric, errors='coerce')

In [79]:
# split the data into test and train data 
X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:, 1:] , df.iloc[:,0], test_size=0.2)

In [80]:
# Scale the data to same rounding
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [81]:
X_train

array([[-1.02565842,  0.20684347, -0.91341287, ...,  0.45900548,
        -0.46644521,  1.92300706],
       [-0.75237481, -1.99815033, -0.76730707, ..., -1.03326992,
         0.76188162, -0.5117394 ],
       [-0.3100498 , -0.87476402, -0.21716566, ...,  1.24156762,
         0.38548386,  3.01613677],
       ...,
       [-0.08747862, -0.02061905, -0.15513191, ..., -0.51731964,
        -0.83974504, -0.42162285],
       [-0.83407816, -1.05580561, -0.86321451, ..., -1.4910913 ,
        -0.12877151, -0.52027114],
       [-0.40302257, -0.65890673, -0.45550585, ..., -0.85798201,
        -0.79792307, -1.05777102]], shape=(455, 30))

In [82]:
# Encode the data to (0,1)
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
Y_test = encoder.transform(Y_test)

In [83]:
Y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [84]:
# convert the numpy array into tenser
X_test_tensor = torch.from_numpy(X_test).float()
X_train_tensor = torch.from_numpy(X_train).float()
Y_test_tensor = torch.from_numpy(Y_test).float()
Y_train_tensor = torch.from_numpy(Y_train).float()

In [85]:
X_train_tensor.shape

torch.Size([455, 30])

In [86]:
Y_train_tensor.shape

torch.Size([455])

In [91]:
# create a custom class in whcih three man functions
class CustomDataSet(Dataset):
# 1:- __init__()
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
        
# 2:- __len__()
    def __len__(self):
        return self.features.shape[0]

# # 3:- __getitem__()
    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]


In [95]:
# create object of dataset class
train_dataset = CustomDataSet(X_train_tensor, Y_train_tensor) 
test_dataset = CustomDataSet(X_test_tensor, Y_test_tensor)

In [96]:
train_dataset[10]

(tensor([ 2.2706,  0.0792,  2.4597,  2.3657,  2.5420,  3.1658,  4.1234,  3.3742,
          2.7547,  1.0465,  2.7311,  0.6107,  3.3297,  2.6398, -0.1593,  3.3520,
          2.2328,  2.0726,  1.2418,  0.4350,  2.4577,  0.3968,  2.9102,  2.5278,
          1.6417,  2.7837,  3.2186,  2.6295,  1.7919,  0.7440]),
 tensor(0.))

In [98]:
# create abject of class Dataloader
train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_dataset = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [101]:
# Define model
import torch.nn as nn
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super(MySimpleNN, self).__init__()
        self.linear = nn.Linear(num_features, 1)  # Linear layer
        self.sigmoid = nn.Sigmoid()  # Sigmoid activation

    def forward(self, features):
        z = self.linear(features)  # Linear transformation
        y_pred = self.sigmoid(z)  # Apply sigmoid
        return y_pred


In [102]:
# important parameters
learning_rate = 0.01
epochs = 15

In [106]:
# Binary cross entropy loss function
Loss = nn.BCELoss()

# use optimazer 
optimazwer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [113]:
# Training Pipline 
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loopabs
for epoch in range(epochs):
    
    # forward pass 
    y_pred = model(batch_features)

    # loss function
    loss = Loss(y_pred,batch_labels.view(-1,1))
    
    # Backward Pass 
    loss.backward()
    
    # Update Parameters
    """ with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad"""
    
    optimazwer.step()

    optimazwer.zero_grad()
    
    print(f'Epoch: {epoch + 1}, Loss:{loss.item()} ')

Epoch: 1, Loss:0.6904346346855164 
Epoch: 2, Loss:0.6904346346855164 
Epoch: 3, Loss:0.6904346346855164 
Epoch: 4, Loss:0.6904346346855164 
Epoch: 5, Loss:0.6904346346855164 
Epoch: 6, Loss:0.6904346346855164 
Epoch: 7, Loss:0.6904346346855164 
Epoch: 8, Loss:0.6904346346855164 
Epoch: 9, Loss:0.6904346346855164 
Epoch: 10, Loss:0.6904346346855164 
Epoch: 11, Loss:0.6904346346855164 
Epoch: 12, Loss:0.6904346346855164 
Epoch: 13, Loss:0.6904346346855164 
Epoch: 14, Loss:0.6904346346855164 
Epoch: 15, Loss:0.6904346346855164 


In [114]:
# Model Evaluation
model.eval()    # set the model to evaluate 
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_dataset:
        # forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.5).float()   # convert the probability to binary prediction

        # calculate the accurcy for current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean()
        accuracy_list.append(batch_accuracy)

# calculate overall accuray
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy.item()}')
 

Accuracy: 0.5047619342803955
